In [2]:
import pandas as pd
df = pd.read_csv('supply_chain_data.csv')
df.head(10)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
5,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
6,skincare,SKU6,4.078333,48,65,7823.476560,Male,11,15,58,...,Kolkata,14,314,24,1.085069,Pending,1.000911,Sea,Route A,134.369097
7,cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
8,cosmetics,SKU8,68.717597,78,150,7517.363211,Female,5,10,15,...,Mumbai,13,769,8,11.423027,Pending,2.709863,Sea,Route B,505.557134
9,skincare,SKU9,64.015733,35,980,4971.145988,Unknown,14,27,83,...,Chennai,29,963,23,47.957602,Pending,3.844614,Rail,Route B,995.929461

In [ ]:
#STEP 2: Data Preprocessing

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load the dataset
data = pd.read_csv('supply_chain_data.csv')

# Encode categorical columns (e.g., Promotion, Weather)
categorical_cols = ['Promotion', 'Weather']  # Add more if needed
for col in categorical_cols:
    if col in data.columns:
        le = LabelEncoder()
        data[col] = le.fit_transform(data[col].astype(str))

# Feature-target split
X = data.drop(['HistoricalSales'], axis=1)  # or 'number_of_product_sold' if not renamed yet
y = data['HistoricalSales']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling (optional for tree-based models, but good practice)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train a Random Forest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

# Predict and evaluate
y_pred = model.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

KeyError: "['HistoricalSales'] not found in axis"

In [4]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

#load the dataset
data = pd.read_csv('supply_chain_data.csv')
data.head()

#simulate Promotion types
promotion_types = ['None','Discount10','BOGO','FlashSale']
data['Promotion'] = np.random.choice(promotion_types, size=len(data))

#Simulate Date (assuming daily data, starting from Jan 1,2016)
data['Date'] = pd.date_range(start = '2016-01-21',periods = len(data), freq = 'D')

#simulate ProductID (eg.,10 different products)
# Make sure the product_type column exists
if 'Product type' not in data.columns:
    raise ValueError("The column 'Product_type' must exist in your dataset")

# Create an empty ProductID column
data['ProductID'] = ''

# Assign unique ProductIDs for each category
haircare_ids = [f'HC{str(i+1).zfill(3)}' for i in range((data['Product type'] == 'haircare').sum())]
skincare_ids = [f'SK{str(i+1).zfill(3)}' for i in range((data['Product type'] == 'skincare').sum())]
cosmetics_ids = [f'CM{str(i+1).zfill(3)}' for i in range((data['Product type'] == 'cosmetics').sum())]

# Fill ProductID column using masking
data.loc[data['Product type'] == 'haircare', 'ProductID'] = haircare_ids
data.loc[data['Product type'] == 'skincare', 'ProductID'] = skincare_ids
data.loc[data['Product type'] == 'cosmetics', 'ProductID'] = cosmetics_ids


#simulate Economic indicators (e.g., random index between 80 and 120)
data['EconomicIndicators'] = np.random.uniform(80,120, size = len(data)).round(2)
                                               
#simulate weather conditions
weather_conditions = ['Sunny','Rainy','Cloudy','Snowy']
data['Weather'] = np.random.choice(weather_conditions, size=len(data))

#Check the updated dataFrame
display(data.head(5))

#(Optional) Save the updated dataset to a new CSV file
data.to_csv('Supply_chain_data_updated.csv',index=False)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Inspection results,Defect rates,Transportation modes,Routes,Costs,Promotion,Date,ProductID,EconomicIndicators,Weather
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Pending,0.226410,Road,Route B,187.752075,None,2016-01-21,HC001,107.15,Cloudy
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Pending,4.854068,Road,Route B,503.065579,None,2016-01-22,SK001,110.17,Cloudy
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Pending,4.580593,Air,Route C,141.920282,Discount10,2016-01-23,HC002,106.17,Cloudy
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Fail,4.746649,Rail,Route A,254.776159,Discount10,2016-01-24,SK002,116.05,Sunny
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Fail,3.145580,Air,Route A,923.440632,FlashSale,2016-01-25,SK003,97.29,Rainy

In [19]:
#Data Cleaning and Feature Engineering

In [8]:
# Identify non-numeric columns in both training and test set
non_numeric_train_cols = X_train.select_dtypes(include=['object']).columns.tolist()
non_numeric_test_cols = X_test.select_dtypes(include=['object']).columns.tolist()

# Get the union of both sets of columns to cover all possibilities
non_numeric_cols = list(set(non_numeric_train_cols) | set(non_numeric_test_cols))

# One-hot encode both sets based on those columns
X_train = pd.get_dummies(X_train, columns=non_numeric_cols)
X_test = pd.get_dummies(X_test, columns=non_numeric_cols)

# Align both datasets to ensure they have the same columns
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

# Standardize the numeric features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

NameError: name 'X_train' is not defined

In [5]:
# Rename 'number_of_product_sold' to 'HistoricalSales'
data.rename(columns = {'Number of products sold' : 'HistoricalSales'}, inplace = True)
display(data.head(5))

,Product type,SKU,Price,Availability,HistoricalSales,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [13]:
#Step 3
#Model Building
#we'll use a neural network for demand forecasting

In [14]:
#Original
#Define the model
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape = [X_train_scaled.shape[1]]),
    layers.Dense(64,activation = 'relu'),
    layers.Dense(32,activation = 'relu'),
    layers.Dense(1) 
])

#Compile the model
model.compile(optimizer = 'adam',loss='mse')

#Train the model
history = model.fit(X_train_scaled, y_train, epochs = 50, validation_split = 0.2)

#Plot training and validation loss
plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label = 'val')
plt.xlabel('Epoch')
plt.ylabel('Mean Squared Error')
plt.legend()
plt.show()

NameError: name 'keras' is not defined

In [7]:
from sklearn.ensemble import RandomForestRegressor

# Initialize the model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the model on the training data
model.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred = model.predict(X_test_scaled)

# Evaluate performance
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R² Score: {r2}")

NameError: name 'X_train_scaled' is not defined

In [1]:
#Step 4
#Model Evaluation
#Evaluate the model on the test set

In [3]:
from sklearn.ensemble import RandomForestRegressor

# Initialize the model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the model
model.fit(X_train_scaled, y_train)

#Evaluate the model
test_predictions = model.predict(X_test_scaled)
mse = mean_squared_error(y_test,test_predictions)
print(f'Mean Squared Error on Test Set: {mse}')

#plot true vs predicted values
plt.scatter(y_test, test_predictions)
plt.xlabel('True Values')
plt.ylabel('Predictions')
plt.title('True vs Predicted Sales')
plt.show()

NameError: name 'X_train_scaled' is not defined

In [ ]:
<div style="background-color:#f0f8ff; padding:10px; border-left:5px solid #1E90FF;">
  <strong>Step 1:</strong> Load the dataset, check missing values, and preprocess features.
</div>

In [ ]:
<h1 style="font-size:32px; color:Black;">Step 1: Data Preparation</h1>

In [ ]:
cd "C:\Users\jianl\Unified Mentor Project_1 Supply Chain"

In [ ]:
# 📦 Demand Forecasting Dashboard

This project predicts the **number of products sold** using a trained Random Forest model based on supply chain features like pricing, inspection, stock levels, weather, and more.

🎯 **Project Goal**: Help supply chain analysts forecast product demand more accurately.

---

## 🚀 Dashboard Preview

The interactive dashboard is built with **Streamlit**.

**👉 [Live Demo](https://share.streamlit.io/yourusername/demand-forecasting-streamlit)**

---

## 🔧 Features

- Upload your own CSV file for predictions
- View model performance (RMSE, R²)
- Visualize feature importance
- See before-and-after tuning results

---

## 🧠 ML Model Info

- Model used: `RandomForestRegressor` (tuned)
- Evaluation metrics: RMSE, R² Score
- Feature selection based on importance

---

## 🗂 Files in this Repo

| File                     | Description                             |
|--------------------------|-----------------------------------------|
| `app.py`                | Streamlit dashboard code                |
| `tuned_random_forest_model.pkl` | Trained model (joblib format) |
| `model_features.pkl`    | Feature columns used during training    |
| `requirements.txt`      | Dependencies for running the app        |
| `rmse_r2_comparison_plot.png` | Performance comparison plot     |
| `sample_input.csv`      | Example input file for testing          |

---

## ▶️ Running the App Locally

```bash
git clone https://github.com/yourusername/demand-forecasting-streamlit.git
cd demand-forecasting-streamlit
pip install -r requirements.txt
streamlit run app.py